- hosts: pi

  vars:
    nodejs_version: 8.x

  tasks:




  #see https://github.com/nodesource/distributions#debinstall
  - name: setup up the nodesource nodejs ppa
    shell: curl -sL https://deb.nodesource.com/setup_{{nodejs_version}} | sudo -E bash -


#  - name: run elm make
#    local_action: shell elm make
#    args:
#      chdir: ./elm/
